[package]
authors = ["Intrepid AI <hello@intrepid.ai>"]
name = "osmto3d-viewer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-fs = "2.1.1"
bevy = { version = "0.13.2", features = ["jpeg"] }
bevy-inspector-egui = "0.23.4"
bevy_mod_raycast = "0.17.0"
